### PR TITLE
Added .Z archive handling

### PR DESCRIPTION
**Pull request by vchepkov**
For Solaris packages come in .Z archive, it's a trivial fix to add support for them

### CODE REVIEW

**Comment by ffrank** [comment]
Thanks @vchepkov and sorry again for delays.

Is this still worth pursuing?

**Comment by vchepkov** [comment]
I am using it on Solaris from my fork, I thought somebody else might need it

**Comment by ffrank** [comment]
OK, cool.

Some observations:

 * this apparently contains the change from #42 
 * there is a merge from master in your branch
 * the branch needs some squashing
 * it cannot merge cleanly anymore

Could you do a `rebase` and take care of the above issues? I would like to commence with a proper review then.

**Comment by vchepkov** [comment]
Will do

**Comment by vchepkov** [comment]
It seems impossible to change a branch of the pull request so I will close this PR and open another one

**Comment by ffrank** [comment]
You can rebuild your branch using `git push -f`. But sure, opening another PR works.

**Pull request closed without merging**
