### PR TITLE
(fix) Add target -d to unzip method

### PR DESCRIPTION
**Pull request by cyberious**
- Fix issue where unzip does not respect the target parameter

### CODE REVIEW

**Comment by cyberious** [comment]
@daenney @nanliu thoughts?

**Comment by daenney** [comment]
So now you can't specify not a target?

**Comment by cyberious** [comment]
The way I read it previously is that this is actually a bug and would be the target it should be expanding to. But that is the way I read it.

**Comment by mkrakowitzer** [comment]
How do you reproduce this issue? I have never experienced it myself. Is it specific to a distro or an os?

**Comment by nibalizer** [comment]
Target is a required parameter so requiring it isn't an issue. However with these execs it looks like they ensure location by setting `cwd` on the exec. Why doesn't that work @cyberious I think @mkrakowitzer is right that we need a better bug report :)

**Comment by nanliu** [comment]
Agreed, cwd should take care of the directory, so need to understand the issue and how to reproduce.

**Pull request closed without merging**
